#include <boost/graph/adjacency_list.hpp>
#include <boost/multi_array.hpp>
#include <boost/bimap.hpp>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <boost/foreach.hpp>
#include <boost/graph/topological_sort.hpp>
#include <boost/utility.hpp>
#include <exception>
